folder: content/blog/ # The folder that required to be parsed
httpsOnly: false # If you want enforce only HTTPS links
pullRequestReview: true # If you want a nice review in your pull requests
ignore: 
  urls: # Array of url to ignore
    - https://github.com 
    - https://www.gogorichie.com/wp-content/*
  files: # Array of markdown file the shouldn't parse
    - */Archieve/*.md # Relative path from the folder shared above
delay:
  'https://gitlab.com': 500 # Perform a pause of 500ms at each call matching the url
