baseURL = "https://www.gogorichie.com/"
languageCode = "en-US"
title = "Richard Lewis"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-124218898-1"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/avataaars.png"
  author = "Richard Lewis"
  description = "DevOps Consultant By Profession & Community Orginzer By Hobby"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "gogorichie"
  Email         = "richard@gogorichie.com"
  Twitter       = "gogorichie"
  LinkedIn      = "gogorichie"
  Facebook      = "RichardLewisJCI"
  RSS           = "/blog/index.xml"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "About"
  identifier = "About"
  weight = 200
  url = "/about/"
