[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.88.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "gogorichie.com"
    # Content-Security-Policy-Report-Only = ""
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = geolocation=(self "https://www.gogorichie.com"), microphone=()
    Strict-Transport-Security = "max-age=2592000"
    Feature-Policy = "vibrate 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none'"